version: '3'
services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32465:32465"
    volumes:
      - ./app/PDF:/app/PDF
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - ./data:/var/lib/postgresql/data
  
  graphql:
    image: my-graphql-app
    ports:
      - '3000:3000'
    restart: always
